// GENERATED by convex-migration-kit from miraside-dashboard (sybpedxhmbalfzvntzcd) at 2026-08-20T07:41:43.033Z.
// Source: pg_catalog.
//
// Review before use. Two deliberate conventions:
//   * Postgres column names are kept verbatim, including `id` — rows keep their
//     original UUID so imports are re-runnable and foreign keys keep working.
//     Convex's own `_id`/`_creationTime` sit alongside them.
//   * Nullable columns are v.union(T, v.null()) rather than v.optional(T),
//     because Postgres exports NULL as `null` and optional means *absent*.
//
// Timestamps are milliseconds since epoch (export-pg converts them in SQL).

import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  ad_accounts: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    fb_account_id: v.string(),
    currency: v.string(),
    timezone_name: v.union(v.string(), v.null()),
    created_at: v.number(),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id_fb_account_id", ["tenant_id","fb_account_id"])
    .index("by_tenant_id", ["tenant_id"])
  ,

  ad_launches: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    name: v.string(),
    status: v.string(),
    format: v.union(v.string(), v.null()),
    ad_count: v.number(),
    thumb_urls: v.array(v.string()),
    created_at: v.number(),
    launched_at: v.union(v.number(), v.null()),
    draft_state: v.any(),
    last_error: v.union(v.string(), v.null()),
    pending: v.any(),
    total_ads: v.union(v.number(), v.null()),
    fb_ad_ids: v.union(v.array(v.string()), v.null()),
    live_status: v.union(v.string(), v.null()),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id_created_at", ["tenant_id","created_at"])
    .index("by_tenant_id", ["tenant_id"]) // FK -> tenants.id
  ,

  ad_presets: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    name: v.string(),
    countries: v.array(v.string()),
    age_min: v.number(),
    age_max: v.number(),
    genders: v.union(v.array(v.number()), v.null()),
    advantage_audience: v.boolean(),
    publisher_platforms: v.array(v.string()),
    default_cta: v.string(),
    default_form_template_id: v.union(v.string(), v.null()),
    created_at: v.number(),
    extra: v.any(),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id", ["tenant_id"])
    .index("by_default_form_template_id", ["default_form_template_id"]) // FK -> lead_form_templates.id
  ,

  ad_status_history: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    ad_id: v.string(),
    status: v.string(),
    changed_at: v.number(),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id", ["tenant_id"])
    .index("by_ad_id", ["ad_id"])
  ,

  ads: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    adset_id: v.string(),
    fb_ad_id: v.string(),
    name: v.union(v.string(), v.null()),
    status: v.union(v.string(), v.null()),
    creative_thumb_url: v.union(v.string(), v.null()),
    created_at: v.number(),
    creative_image_url: v.union(v.string(), v.null()),
    deleted_at: v.union(v.number(), v.null()),
    effective_status: v.union(v.string(), v.null()),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id_fb_ad_id", ["tenant_id","fb_ad_id"])
    .index("by_tenant_id", ["tenant_id"])
    .index("by_fb_ad_id", ["fb_ad_id"])
    .index("by_adset_id", ["adset_id"]) // FK -> adsets.id
  ,

  adsets: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    campaign_id: v.string(),
    fb_adset_id: v.string(),
    name: v.union(v.string(), v.null()),
    status: v.union(v.string(), v.null()),
    budget_level: v.union(v.literal("cbo"), v.literal("abo"), v.null()),
    created_at: v.number(),
    deleted_at: v.union(v.number(), v.null()),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id_fb_adset_id", ["tenant_id","fb_adset_id"])
    .index("by_tenant_id", ["tenant_id"])
    .index("by_campaign_id", ["campaign_id"]) // FK -> campaigns.id
  ,

  audience_segment_daily: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    ad_id: v.string(),
    date: v.string(),
    segment: v.union(v.literal("new"), v.literal("engaged"), v.literal("existing")),
    spend: v.number(),
    results: v.number(),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id_ad_id_date_segment", ["tenant_id","ad_id","date","segment"])
    .index("by_tenant_id", ["tenant_id"])
    .index("by_ad_id", ["ad_id"]) // FK -> ads.id
  ,

  campaigns: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    ad_account_id: v.string(),
    fb_campaign_id: v.string(),
    name: v.union(v.string(), v.null()),
    status: v.union(v.string(), v.null()),
    budget_level: v.union(v.literal("cbo"), v.literal("abo"), v.null()),
    created_at: v.number(),
    deleted_at: v.union(v.number(), v.null()),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id_fb_campaign_id", ["tenant_id","fb_campaign_id"])
    .index("by_tenant_id", ["tenant_id"])
    .index("by_ad_account_id", ["ad_account_id"]) // FK -> ad_accounts.id
  ,

  cold_call_activities: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    contact_id: v.string(),
    rep: v.union(v.string(), v.null()),
    called_at: v.number(),
    channel: v.string(),
    disposition: v.union(v.string(), v.null()),
    reached_decision_maker: v.union(v.boolean(), v.null()),
    objection: v.union(v.string(), v.null()),
    next_step: v.union(v.string(), v.null()),
    follow_up_at: v.union(v.number(), v.null()),
    notes: v.union(v.string(), v.null()),
    created_at: v.number(),
    created_by: v.union(v.string(), v.null()),
  })
    .index("by_pg_id", ["id"])
    .index("by_contact_id_called_at", ["contact_id","called_at"])
    .index("by_tenant_id_called_at", ["tenant_id","called_at"])
    .index("by_tenant_id", ["tenant_id"]) // FK -> tenants.id
    .index("by_contact_id", ["contact_id"]) // FK -> cold_call_contacts.id
  ,

  cold_call_contacts: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    source_tab: v.string(),
    sheet_row: v.union(v.number(), v.null()),
    dedupe_key: v.string(),
    first_name: v.union(v.string(), v.null()),
    last_name: v.union(v.string(), v.null()),
    full_name: v.union(v.string(), v.null()),
    role: v.union(v.string(), v.null()),
    tier: v.union(v.string(), v.null()),
    seniority: v.union(v.string(), v.null()),
    department: v.union(v.string(), v.null()),
    email: v.union(v.string(), v.null()),
    email_norm: v.union(v.string(), v.null()),
    phone: v.union(v.string(), v.null()),
    phone_norm: v.union(v.string(), v.null()),
    country: v.union(v.string(), v.null()),
    person_linkedin: v.union(v.string(), v.null()),
    company_name: v.union(v.string(), v.null()),
    company_short_name: v.union(v.string(), v.null()),
    company_linkedin: v.union(v.string(), v.null()),
    website: v.union(v.string(), v.null()),
    industry_group: v.union(v.string(), v.null()),
    industry: v.union(v.string(), v.null()),
    niche: v.union(v.string(), v.null()),
    employees: v.union(v.number(), v.null()),
    company_size: v.union(v.string(), v.null()),
    company_about: v.union(v.string(), v.null()),
    company_industry_li: v.union(v.string(), v.null()),
    call_status: v.string(),
    assigned_user: v.union(v.string(), v.null()),
    notes: v.union(v.string(), v.null()),
    attempts: v.number(),
    reached_decision_maker: v.union(v.boolean(), v.null()),
    last_outcome: v.union(v.string(), v.null()),
    last_attempt_at: v.union(v.number(), v.null()),
    next_follow_up_at: v.union(v.number(), v.null()),
    sheet_synced_at: v.union(v.number(), v.null()),
    pushed_at: v.union(v.number(), v.null()),
    deleted_from_sheet_at: v.union(v.number(), v.null()),
    created_at: v.number(),
    updated_at: v.number(),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id_dedupe_key", ["tenant_id","dedupe_key"])
    .index("by_tenant_id_call_status", ["tenant_id","call_status"])
    .index("by_tenant_id_assigned_user", ["tenant_id","assigned_user"])
    .index("by_tenant_id_next_follow_up_at", ["tenant_id","next_follow_up_at"])
    .index("by_tenant_id_niche", ["tenant_id","niche"])
    .index("by_tenant_id_email_norm", ["tenant_id","email_norm"])
    .index("by_tenant_id_phone_norm", ["tenant_id","phone_norm"])
    .index("by_tenant_id", ["tenant_id"]) // FK -> tenants.id
  ,

  connections: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    provider: v.union(v.literal("facebook"), v.literal("ghl")),
    status: v.string(),
    last_completed_date: v.union(v.string(), v.null()),
    sync_status: v.union(v.string(), v.null()),
    last_error: v.union(v.string(), v.null()),
    created_at: v.number(),
    updated_at: v.number(),
    last_synced_at: v.union(v.number(), v.null()),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id_provider", ["tenant_id","provider"])
    .index("by_tenant_id", ["tenant_id"])
  ,

  deprecated_lead_form_settings: defineTable({
    tenant_id: v.string(),
    privacy_url: v.string(),
    thank_you_headline: v.string(),
    thank_you_message: v.string(),
    thank_you_url: v.string(),
    thank_you_button: v.string(),
    updated_at: v.number(),
    updated_by: v.union(v.string(), v.null()),
  })
    .index("by_tenant_id", ["tenant_id"])
  ,

  fb_event_health: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    account_id: v.union(v.string(), v.null()),
    event_name: v.string(),
    emq_score: v.union(v.number(), v.null()),
    checked_at: v.number(),
    day: v.string(),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id", ["tenant_id"])
    .index("by_tenant_id_account_id_event_name_day", ["tenant_id","account_id","event_name","day"])
    .index("by_account_id", ["account_id"]) // FK -> ad_accounts.id
  ,

  fb_insights_daily: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    ad_id: v.string(),
    date: v.string(),
    spend: v.number(),
    impressions: v.number(),
    clicks: v.number(),
    link_clicks: v.number(),
    ctr: v.union(v.number(), v.null()),
    link_ctr: v.union(v.number(), v.null()),
    cpc: v.union(v.number(), v.null()),
    cpm: v.union(v.number(), v.null()),
    landing_page_views: v.union(v.number(), v.null()),
    video_3s_views: v.union(v.number(), v.null()),
    thruplays: v.union(v.number(), v.null()),
    fb_leads: v.union(v.number(), v.null()),
    reach: v.union(v.number(), v.null()),
    frequency: v.union(v.number(), v.null()),
    incremental_conversions: v.union(v.number(), v.null()),
    actions_json: v.any(),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id_ad_id_date", ["tenant_id","ad_id","date"])
    .index("by_tenant_id", ["tenant_id"])
    .index("by_ad_id_date", ["ad_id","date"])
    .index("by_ad_id", ["ad_id"]) // FK -> ads.id
  ,

  fb_insights_window: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    ad_id: v.string(),
    window_start: v.string(),
    window_end: v.string(),
    reach: v.union(v.number(), v.null()),
    frequency: v.union(v.number(), v.null()),
    impressions: v.union(v.number(), v.null()),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id_ad_id_window_start_window_end", ["tenant_id","ad_id","window_start","window_end"])
    .index("by_tenant_id", ["tenant_id"])
    .index("by_ad_id", ["ad_id"]) // FK -> ads.id
  ,

  ghl_contacts: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    ghl_contact_id: v.string(),
    created_at: v.union(v.number(), v.null()),
    fbclid: v.union(v.string(), v.null()),
    fb_ad_id: v.union(v.string(), v.null()),
    fb_adset_id: v.union(v.string(), v.null()),
    fb_campaign_id: v.union(v.string(), v.null()),
    attribution_source: v.union(v.string(), v.null()),
    synced_at: v.number(),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id_ghl_contact_id", ["tenant_id","ghl_contact_id"])
    .index("by_tenant_id", ["tenant_id"])
    .index("by_fb_ad_id", ["fb_ad_id"])
  ,

  ghl_field_pins: defineTable({
    tenant_id: v.string(),
    fingerprint: v.string(),
    ghl_field_id: v.string(),
    label: v.union(v.string(), v.null()),
    created_at: v.number(),
  })
    .index("by_tenant_id_fingerprint", ["tenant_id","fingerprint"])
  ,

  ghl_opportunities: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    ghl_opp_id: v.string(),
    contact_id: v.union(v.string(), v.null()),
    pipeline_id: v.union(v.string(), v.null()),
    stage: v.union(v.string(), v.null()),
    stage_changed_at: v.union(v.number(), v.null()),
    monetary_value: v.union(v.number(), v.null()),
    status: v.union(v.string(), v.null()),
    created_at: v.union(v.number(), v.null()),
    closed_at: v.union(v.number(), v.null()),
    synced_at: v.number(),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id_ghl_opp_id", ["tenant_id","ghl_opp_id"])
    .index("by_tenant_id", ["tenant_id"])
    .index("by_contact_id", ["contact_id"])
  ,

  lead_exclusions: defineTable({
    tenant_id: v.string(),
    meta_lead_id: v.string(),
    reason: v.union(v.string(), v.null()),
    created_at: v.number(),
    fb_ad_id: v.union(v.string(), v.null()),
    lead_date: v.union(v.string(), v.null()),
  })
    .index("by_tenant_id_meta_lead_id", ["tenant_id","meta_lead_id"])
    .index("by_tenant_id", ["tenant_id"]) // FK -> tenants.id
  ,

  lead_form_templates: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    name: v.string(),
    questions: v.any(),
    follow_up_url: v.union(v.string(), v.null()),
    privacy_url: v.union(v.string(), v.null()),
    meta_form_id: v.union(v.string(), v.null()),
    created_at: v.number(),
    greeting: v.any(),
    thank_you: v.any(),
    is_audit: v.boolean(),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id", ["tenant_id"])
  ,

  lead_meetings: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    lead_id: v.string(),
    ghl_appointment_id: v.union(v.string(), v.null()),
    ghl_contact_id: v.union(v.string(), v.null()),
    starts_at: v.number(),
    ends_at: v.union(v.number(), v.null()),
    title: v.union(v.string(), v.null()),
    link: v.union(v.string(), v.null()),
    calendar_id: v.union(v.string(), v.null()),
    attendance: v.union(v.literal("scheduled"), v.literal("showed"), v.literal("no_show"), v.literal("cancelled")),
    outcome: v.union(v.literal("follow_up_booked"), v.literal("proposal_sent"), v.literal("won"), v.literal("disqualified"), v.null()),
    disqualify_reason: v.union(v.literal("no_budget"), v.literal("not_icp"), v.literal("bad_timing"), v.literal("went_elsewhere"), v.literal("other"), v.null()),
    notes: v.union(v.string(), v.null()),
    outcome_set_at: v.union(v.number(), v.null()),
    last_seen_at: v.union(v.number(), v.null()),
    created_at: v.number(),
    updated_at: v.number(),
    confirmed_at: v.union(v.number(), v.null()),
  })
    .index("by_pg_id", ["id"])
    .index("by_lead_id_ghl_appointment_id", ["lead_id","ghl_appointment_id"]) // was UNIQUE WHERE ghl_appointment_id IS NOT NULL — re-enforce uniqueness in the mutation
    .index("by_lead_id_starts_at", ["lead_id","starts_at"])
    .index("by_tenant_id_starts_at", ["tenant_id","starts_at"])
    .index("by_tenant_id_attendance", ["tenant_id","attendance"]) // was partial WHERE attendance = ANY (ARRAY['no_show'::text, 'cancelled'::text]) — apply as a filter at read time
    .index("by_lead_id", ["lead_id"]) // was UNIQUE WHERE ghl_appointment_id IS NULL — re-enforce uniqueness in the mutation
  ,

  leads: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    meta_lead_id: v.string(),
    form_id: v.union(v.string(), v.null()),
    fb_ad_id: v.union(v.string(), v.null()),
    fb_adset_id: v.union(v.string(), v.null()),
    fb_campaign_id: v.union(v.string(), v.null()),
    ad_name: v.union(v.string(), v.null()),
    full_name: v.union(v.string(), v.null()),
    email: v.union(v.string(), v.null()),
    email_norm: v.union(v.string(), v.null()),
    phone: v.union(v.string(), v.null()),
    phone_norm: v.union(v.string(), v.null()),
    answers: v.any(),
    created_time: v.union(v.number(), v.null()),
    ghl_contact_id: v.union(v.string(), v.null()),
    ghl_tags: v.array(v.string()),
    qualification: v.union(v.literal("qualified"), v.literal("unqualified"), v.literal("pending")),
    matched_at: v.union(v.number(), v.null()),
    synced_at: v.number(),
    created_at: v.number(),
    ghl_name: v.union(v.string(), v.null()),
    source: v.string(),
    stage: v.union(v.string(), v.null()),
    slack_ts: v.union(v.string(), v.null()),
    slack_channel: v.union(v.string(), v.null()),
    started_at: v.union(v.number(), v.null()),
    completed_at: v.union(v.number(), v.null()),
    channel: v.union(v.string(), v.null()),
    source_detail: v.union(v.string(), v.null()),
    audit_qualified: v.union(v.boolean(), v.null()),
    ghl_pushed_at: v.union(v.number(), v.null()),
    cr_fired_at: v.union(v.number(), v.null()),
    cr_event_id: v.union(v.string(), v.null()),
    audit_pushed_at: v.union(v.number(), v.null()),
    audit_url: v.union(v.string(), v.null()),
    phone_override: v.union(v.string(), v.null()),
    additional_email: v.union(v.string(), v.null()),
    additional_phone: v.union(v.string(), v.null()),
    email_override: v.union(v.string(), v.null()),
    first_name_override: v.union(v.string(), v.null()),
    last_name_override: v.union(v.string(), v.null()),
    call_state: v.union(v.literal("none"), v.literal("contacted"), v.literal("no_answer"), v.literal("invalid_phone"), v.literal("follow_up"), v.literal("meeting_booked")),
    call_attempts: v.number(),
    last_call_attempt_at: v.union(v.number(), v.null()),
    website_override: v.union(v.string(), v.null()),
    ghl_appointment_id: v.union(v.string(), v.null()),
    appointment_at: v.union(v.number(), v.null()),
    appointment_end_at: v.union(v.number(), v.null()),
    appointment_status: v.union(v.string(), v.null()),
    appointment_title: v.union(v.string(), v.null()),
    appointment_link: v.union(v.string(), v.null()),
    ghl_task_id: v.union(v.string(), v.null()),
    task_title: v.union(v.string(), v.null()),
    task_due_at: v.union(v.number(), v.null()),
    tags_updated_at: v.union(v.number(), v.null()),
    task_count: v.number(),
    notes_count: v.number(),
    deleted_at: v.union(v.number(), v.null()),
    first_call_at: v.union(v.number(), v.null()),
    ghl_opportunity_id: v.union(v.string(), v.null()),
    opportunity_value: v.union(v.number(), v.null()),
    opportunity_status: v.union(v.string(), v.null()),
    opportunity_won_at: v.union(v.number(), v.null()),
    notes_cache: v.any(),
    company: v.union(v.string(), v.null()),
    company_fetched_at: v.union(v.number(), v.null()),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id_meta_lead_id", ["tenant_id","meta_lead_id"])
    .index("by_tenant_id_fb_ad_id", ["tenant_id","fb_ad_id"])
    .index("by_tenant_id_qualification", ["tenant_id","qualification"])
    .index("by_tenant_id_created_time", ["tenant_id","created_time"])
    .index("by_tenant_id_email_norm", ["tenant_id","email_norm"])
    .index("by_tenant_id_phone_norm", ["tenant_id","phone_norm"])
    .index("by_tenant_id", ["tenant_id"]) // was partial WHERE deleted_at IS NULL — apply as a filter at read time
  ,

  pipeline_stage_map: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    ghl_pipeline_id: v.string(),
    stage_name: v.string(),
    canonical_stage: v.union(v.literal("lead"), v.literal("booked"), v.literal("held_1"), v.literal("held_2"), v.literal("va"), v.literal("won"), v.literal("lost")),
    created_at: v.number(),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id_ghl_pipeline_id_stage_name", ["tenant_id","ghl_pipeline_id","stage_name"])
    .index("by_tenant_id", ["tenant_id"])
  ,

  question_labels: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    question: v.string(),
    label: v.string(),
    created_at: v.number(),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id_question", ["tenant_id","question"])
    .index("by_tenant_id", ["tenant_id"]) // FK -> tenants.id
  ,

  setting_definitions: defineTable({
    key: v.string(),
    label: v.string(),
    description: v.union(v.string(), v.null()),
    value_type: v.union(v.literal("currency"), v.literal("percent"), v.literal("days"), v.literal("ratio"), v.literal("count"), v.literal("enum"), v.literal("boolean"), v.literal("url"), v.literal("text"), v.literal("longtext")),
    unit: v.union(v.string(), v.null()),
    default_value: v.any(),
    suggested_min: v.any(),
    suggested_max: v.any(),
    enum_options: v.any(),
    used_by: v.union(v.string(), v.null()),
    created_at: v.number(),
  })
    .index("by_key", ["key"])
  ,

  sync_state: defineTable({
    tenant_id: v.string(),
    kind: v.string(),
    last_success_at: v.number(),
  })
    .index("by_tenant_id_kind", ["tenant_id","kind"])
  ,

  tenant_settings: defineTable({
    tenant_id: v.string(),
    key: v.string(),
    value: v.any(),
    updated_by: v.union(v.string(), v.null()),
    updated_at: v.number(),
  })
    .index("by_tenant_id_key", ["tenant_id","key"])
    .index("by_tenant_id", ["tenant_id"]) // FK -> tenants.id
    .index("by_key", ["key"]) // FK -> setting_definitions.key
  ,

  tenants: defineTable({
    id: v.string(),
    name: v.string(),
    created_at: v.number(),
  })
    .index("by_pg_id", ["id"])
  ,

  users: defineTable({
    id: v.string(),
    tenant_id: v.string(),
    role: v.string(),
    created_at: v.number(),
  })
    .index("by_pg_id", ["id"])
    .index("by_tenant_id", ["tenant_id"])
  ,
});
